[build]

command="npm run build"

publish=""

[[redirects]]
  from = "https://silly-hugle-b3671e.netlify.app/"
  to = "/allnotas"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Role = ["admin"]}

  [[redirects]]
  from = "https://silly-hugle-b3671e.netlify.app/"
  to = "notas"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}