[build]

command="npm run build"

publish=""

base="/"

[[redirects]]
  from = "/*"
  to = "/allnotas"
  query = {path = ":path"}

  [[redirects]]
  from = "/*"
  to = "notas"
  query = {path = ":path"}
